
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Gem,
  Users,
  Sparkles,
  ArrowRight,
  History,
  ShieldCheck,
} from "lucide-react";
import { getDashboardStats } from "../services/recommendationService";
import { useLoading } from "../context/LoadingContext";
import { useToast } from "../context/ToastContext";

const StatCard = ({ icon: Icon, title, value, subtitle }) => (
  <motion.div
    whileHover={{ y: -6, scale: 1.02 }}
    className="rounded-3xl border border-amber-100 bg-white/75 p-6 shadow-lg backdrop-blur"
  >
    <div className="flex items-center justify-between">
      <div>
        <p className="text-sm text-gray-500">{title}</p>
        <h3 className="mt-2 text-4xl font-bold text-[#3F2E1E]">{value}</h3>
        <p className="mt-2 text-sm text-gray-500">{subtitle}</p>
      </div>
      <div className="rounded-2xl bg-amber-100 p-4">
        <Icon className="h-8 w-8 text-amber-600" />
      </div>
    </div>
  </motion.div>
);

export default function Dashboard() {
  const navigate = useNavigate();
  const { startLoading, stopLoading } = useLoading();
  const { showError } = useToast();

  const [stats, setStats] = useState({
    totalUsers: 0,
    totalRecommendations: 0,
  });

  useEffect(() => {
    let mounted = true;
    (async () => {
      try {
        startLoading("Loading dashboard...");
        const res = await getDashboardStats();
        if (mounted) setStats(res.data);
      } catch (e) {
        if (mounted) showError("Failed to load dashboard.");
      } finally {
        stopLoading();
      }
    })();
    return () => {
      mounted = false;
      stopLoading();
    };
  }, []);

  return (
    <div className="min-h-[87.5vh] bg-gradient-to-br from-[#fffdf8] via-[#fff8ef] to-[#f6ead0]">
      <div className="mx-auto max-w-7xl px-8 py-10">
        <motion.div
          initial={{opacity:0,y:20}}
          animate={{opacity:1,y:0}}
          className="rounded-[36px] bg-white/70 backdrop-blur-xl border border-amber-100 shadow-2xl p-10"
        >
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-8">
            <div>
              <span className="inline-flex items-center gap-2 rounded-full bg-amber-100 px-4 py-2 text-amber-700">
                <Sparkles className="h-4 w-4"/> GemAura AI
              </span>
              <h1 className="mt-5 text-5xl font-bold text-[#3F2E1E]">
                Discover the Perfect Gemstone
              </h1>
              <p className="mt-4 max-w-2xl text-lg text-gray-600">
                Personalized AI-powered gemstone recommendations using your birth details and life goals.
              </p>

              <div className="mt-8 flex flex-wrap gap-4">
                <button
                  onClick={() => navigate("/recommendation")}
                  className="rounded-2xl bg-gradient-to-r from-amber-500 to-yellow-500 px-6 py-4 font-semibold text-white shadow-lg hover:scale-105 transition"
                >
                  Get Recommendation
                </button>

                <button
                  onClick={() => navigate("/history")}
                  className="rounded-2xl border border-amber-200 bg-white px-6 py-4 font-semibold text-[#3F2E1E] hover:bg-amber-50 transition flex items-center gap-2"
                >
                  <History className="h-5 w-5"/> View History
                </button>
              </div>
            </div>

            <motion.div
              animate={{ rotate: [0,4,-4,0] }}
              transition={{ repeat: Infinity, duration: 5 }}
              className="flex justify-center"
            >
              <div className="rounded-full bg-amber-100 p-10 shadow-xl">
                <Gem className="h-28 w-28 text-amber-600"/>
              </div>
            </motion.div>
          </div>
        </motion.div>

        <div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          <StatCard
            icon={Users}
            title="Trusted Users"
            value={stats.totalUsers}
            subtitle="Growing community"
          />
          <StatCard
            icon={Gem}
            title="Recommendations"
            value={stats.totalRecommendations}
            subtitle="Generated by AI"
          />
          <StatCard
            icon={ShieldCheck}
            title="AI Accuracy"
            value="98.7%"
            subtitle="Estimated confidence"
          />
          <StatCard
            icon={Sparkles}
            title="Gemstones"
            value="25+"
            subtitle="Curated catalog"
          />
        </div>

        <motion.div
          initial={{opacity:0}}
          animate={{opacity:1}}
          transition={{delay:0.3}}
          className="mt-10 rounded-3xl bg-gradient-to-r from-amber-500 to-yellow-500 p-8 text-white shadow-xl"
        >
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div>
              <h2 className="text-3xl font-bold">Ready for your personalized insight?</h2>
              <p className="mt-2 opacity-90">
                Generate an AI-backed gemstone recommendation in seconds.
              </p>
            </div>
            <button
              onClick={() => navigate("/recommendation")}
              className="rounded-2xl bg-white px-6 py-4 font-semibold text-amber-700 flex items-center gap-2 hover:scale-105 transition"
            >
              Start Now <ArrowRight className="h-5 w-5"/>
            </button>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
